// src/pages/me/index.tsx
import React from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import { AiOutlineArrowRight, AiOutlineArrowUp } from 'react-icons/ai';

const Me: NextPage = () => {
  return (
    <>
      <Head>
        <title>joaogomes.dev | Me</title>
        <meta name="description" content="My own peace of the internet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="about" className="scroll-smooth w-screen 3xs:max-w-2lg md:max-w-4xl">
        <div className="flex flex-col md:flex-row justify-between items-center sm:items-start gap-10 md:gap-0">
          <div className="flex flex-col gap-4 self-start">
            <h1 className="font-bold text-4xl">About me.</h1>
            <div className="flex flex-col gap-4 3xs:max-w-sm md:max-w-md">
            <p className="text-zinc-500 font-mono">Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.</p>
            <p className="text-zinc-500 font-mono">Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.</p>
            <p className="text-zinc-500 font-mono">Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.</p>
            <p className="text-zinc-500 font-mono">Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.</p>
            <p className="text-zinc-500 font-mono">Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.</p>
            </div>
          </div>
          
          <div>

          <Image
            src="/me.png"
            alt="Me"
            layout="fixed"
            width={345}
            height={490}
            className="rounded-3xl 3xl:mr-2 md:mr-0"
          />
          </div>
        </div>
        <div className="flex items-start">

        <div className="mt-20 flex flex-col md:flex-row justify-between gap-8 md:gap-0">
            <div className="max-w-lg flex flex-col gap-4">
              <h1 className="font-bold text-4xl">Bio.</h1>
              <p className="text-zinc-500 text-xl">
                Enthusiastic about Web / Mobile development
              </p>
              <p className="text-zinc-500 text-xl">
                Lets share knowledge to create a better world 🌍
              </p>
            </div>

            <div className="self-end">

            <Image
              src="/memoji.png"
              alt="MeMoji"
              width={141}
              height={208}
              />
              </div>
          </div>
              </div>



        <div className="mt-20">
          <div className="flex flex-col gap-4">
            <h1 className="font-bold text-4xl">Professional path.</h1>
            <p className="text-zinc-500 text-lg">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            </p>

            <div className="mt-10 flex flex-col gap-8 items-start">

              <div className="gap-1">
                <p className="text-2xl font-bold text-blue-500">🏨 Fullstack Web Developer</p>
                <div className="text-lg">
                  <a href="https://noniussolutions.com/" className="underline underline-offset-4" target="blank">Nonius Software</a>
                  <span> • </span>
                  Maia , Portugal 🇵🇹
                </div>
                <div className="mt-1">
                  Mar to Jul <span>  •  </span> 2022
                </div>
              </div>

              <div className="gap-1">
                <p className="text-2xl font-bold text-yellow-500">🪪  Web Developer - Internship</p>
                <div className="text-lg">
                  <a href="https://www.sorema.pt" className="underline underline-offset-4" target="blank">Unizon</a>
                  <span> • </span>
                  Remote | Porto, Portugal 🇵🇹
                </div>
                <div className="mt-1">
                  Mar to Jul <span>  •  </span> 2022
                </div>
              </div>
              <div className="gap-1">
                <p className="text-2xl font-bold text-violet-500">🌐 Web Developer -Internship</p>
                <div className="text-lg">
                  <a href="https://www.wecreateyou.pt" className="underline underline-offset-4" target="blank">WeCreateYou</a>
                  <span> • </span>
                  São Felix da Marinha, Portugal 🇵🇹
                </div>
                <div className="mt-1">
                  Mar to Jul <span>  •  </span> 2020
                </div>
              </div>
              <div className="gap-1">
                <p className="text-2xl font-bold text-red-500">🏭 Techical Support - Internship</p>
                <div className="text-lg">
                  <a href="https://www.sorema.pt" className="underline underline-offset-4" target="blank">Sorema</a>
                  <span> • </span>
                  Espinho, Portugal 🇵🇹
                </div>
                <div className="mt-1">
                  Mar to Jul <span>  •  </span> 2019
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-20 flex justify-between items-end w-full">

          <Link href="#about">
            <span className="border-2 border-indigo-500 p-4 rounded-full cursor-pointer hidden sm:inline-flex">
              <AiOutlineArrowUp size={28} className="text-[#FBAE95]" />
            </span>
          </Link>

          <div className="flex justify-center items-center gap-2">
            <Link href="/me/what-i-use">
              <h1 className="text-4xl hover-underline-animation  after:bg-gray-800 after:dark:bg-white cursor-pointer ">What i use.</h1>
            </Link>
            <Link href="/me/what-i-use">
              <span className="border-2 border-indigo-500 p-3 rounded-full cursor-pointer">
                <AiOutlineArrowRight size={24} className="text-[#FBAE95]" />
              </span>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default Me;

// src/routes/me/+page.svelte
<script>
  import me from '$lib/assets//me.png'
  import memoji from '$lib/assets//memoji.png'
</script>

<div id="about" class="scroll-smooth w-screen 3xs:max-w-2lg md:max-w-4xl">
  <div class="flex flex-col md:flex-row justify-between items-center sm:items-start gap-10 md:gap-0">
    <div class="flex flex-col gap-4 self-start">
      <h1 class="font-bold text-4xl">About me.</h1>
      <div class="flex flex-col gap-4 3xs:max-w-sm md:max-w-md">
      <p class="text-zinc-400 font-mono">My name is <span class="text-purple-500 font-semibold">João Gomes</span>, Im 20 years old and i live in Espinho, Portugal. 🇵🇹</p>
      <p class="text-zinc-400 font-mono">In my free time, I enjoy playing video games, watching movies, listening to music and most importantly, learning new things.</p>
      <p class="text-zinc-400 font-mono">I am on a journey to become a software developer with the goal of creating high-quality software that can change peoples lives.</p>
      <p class="text-zinc-400 font-mono">I am always open to meeting new people and sharing knowledge.</p>
      <p class="text-zinc-400 font-mono"> I would describe myself as <span class="font-semibold">proactive</span>, <span class="font-semibold">dedicated</span> and <span class="font-semibold"> motivated</span>.</p>
      </div>
    </div>
    
    <div>
      <img
        src={me}
        class="rounded-3xl 3xl:mr-2 md:mr-0"
        alt="Me"
        width="345"
        height="490"
      />
    </div>
  </div>
  <div class="mt-20 flex flex-col md:flex-row justify-between gap-8 md:gap-0 w-full items-center md:items-start">
      <div class="max-w-lg flex flex-col gap-4 ">
        <h1 class="font-bold text-4xl">Bio.</h1>
        <p class="text-zinc-500 text-xl">
          Enthusiastic about Web / Mobile development.
        </p>
        <p class="text-zinc-500 text-xl">
          Lets share knowledge to create a better world. <span class="ml-2">🌍</span>
        </p>
      </div>

      <div>

        <img
          src={memoji}
          alt="Memoji"
        />
      </div>
  </div>

  <div class="mt-20">
    <div class="flex flex-col gap-4">
      <h1 class="font-bold text-4xl">Professional path.</h1>
      <p class="text-zinc-500 text-lg">
      This is my path since I began in the world of programming. I hope to learn even more and experience many more incredible places along the way, I am dedicated to always improve and strive for excellence.
      </p>
      <p class="text-zinc-500 text-lg">
      The journey so far has been filled with challenges and obstacles, but also with a lot of growth and satisfaction. 
      </p>
      
      <p class="text-zinc-500 text-lg">
      I am looking forward to what the future holds. <span class="ml-2">🚀</span>
      </p>

      <div class="mt-10 flex flex-col gap-8 items-start">

        

        
        
        <div class="gap-1">
          <p class="text-2xl font-bold text-red-500">🏭 Techical Support - Internship</p>
          <div class="text-lg">
            <a href="https://www.sorema.pt" class="underline underline-offset-4" target="blank">Sorema</a>
            <span> • </span>
            Espinho, Portugal 🇵🇹
          </div>
          <div class="mt-1">
            Mar to Jul <span>  •  </span> 2019
          </div>
        </div>

        <div class="gap-1">
          <p class="text-2xl font-bold text-violet-500">🌐 Web Developer -Internship</p>
          <div class="text-lg">
            <a href="https://www.wecreateyou.pt" class="underline underline-offset-4" target="blank">WeCreateYou</a>
            <span> • </span>
            São Felix da Marinha, Portugal 🇵🇹
          </div>
          <div class="mt-1">
            Mar to Jul <span>  •  </span> 2020
          </div>
        </div>

        <div class="gap-1">
          <p class="text-2xl font-bold text-yellow-500">🪪  Web Developer - Internship</p>
          <div class="text-lg">
            <a href="https://www.sorema.pt" class="underline underline-offset-4" target="blank">Unizon</a>
            <span> • </span>
            Remote | Porto, Portugal 🇵🇹
          </div>
          <div class="mt-1">
            Mar to Jul <span>  •  </span> 2022
          </div>
        </div>

        <div class="gap-1">
          <p class="text-2xl font-bold text-blue-500">🏨 Fullstack Web Developer</p>
          <div class="text-lg">
            <a href="https://noniussolutions.com/" class="underline underline-offset-4" target="blank">Nonius Software</a>
            <span> • </span>
            Maia , Portugal 🇵🇹
          </div>
          <div class="mt-1">
            Sep <span>  •  </span> 2022 to Feb <span>  •  </span> 2023
          </div>
        </div>

        <div class="gap-1">
          <p class="text-2xl font-bold text-gray-200">🥚 Front-end Developer</p>
          <div class="text-lg">
            <a href="https://significa.co/" class="underline underline-offset-4" target="blank">Significa</a>
            <span> • </span>
            Porto , Portugal 🇵🇹
          </div>
          <div class="mt-1">
            Feb 2023 <span>  •  </span> Current
          </div>
        </div>

        

        
      </div>
    </div>
  </div>


  <div class="mt-20 flex flex-col md:flex-row justify-between gap-8 md:gap-0 w-full items-center md:items-start">
      <div class="flex flex-col">
        <h1 class="font-bold text-4xl">Experience summary.</h1>
        <p class="text-zinc-400 text-lg mt-6">
          I started my study journey in Development during high school, in the professional course of “Management and Programming of Computer Systems” where I had the opportunity to carry out two curricular internships.
        </p>
        <p class="text-zinc-400 text-lg mt-6">
          At the end of the last high school year, I started my self-taught studies in Web Development through a Node, React and React Native bootcamp provided by Rocketseat. This experience enabled me to develop a more appropriate study method according to the needs of the market and focused on the practical side, where I made different projects (such as Ticked, Happy, Lets Play that can be found on my Github).
        </p>
        <p class="text-zinc-400 text-lg mt-6">
          After concluding high school and the Rocketseat bootcamp (2020), I joined the “Professional Superior Technical Course in Agile Software Development” carried out by ISEP, where were addressed topics and contents of Computer Engineering with a focus on agile development. The course lasted two years (2020-2022) with an internship in the last semester. During this internship, I was responsible for an entire project, going through all stages of development, from gathering requirements to implementation. More specifically, I used React for the frontend and Elixir for the backend.
        </p>
        <p class="text-zinc-400 text-lg mt-6">
          From September 2022 to February 2023, I worked at Nonius, building full-stack applications using a diverse stack including Vue, PHP, JavaScript, and Python with Django.
        </p>
        <p class="text-zinc-400 text-lg mt-6">
          Currently, I am working at Significa, where I am involved in building exceptional and high-quality projects.
        </p>
        <p class="text-zinc-400 text-lg mt-6">
          Most importantly, I am always looking to evolve and learn! 🚀
        </p>


      </div>
  </div>
<!-- 
  <div class="mt-20 flex justify-between items-end w-full">

    <Link href="#about">
      <span class="border-2 border-indigo-500 p-4 rounded-full cursor-pointer hidden sm:inline-flex">
        <AiOutlineArrowUp size={28} class="text-[#FBAE95]" />
      </span>
    </Link>

    <div class="flex justify-center items-center gap-2">
      <Link href="/me/what-i-use">
        <h1 class="text-4xl hover-underline-animation  after:bg-gray-800 after:dark:bg-white cursor-pointer ">What i use.</h1>
      </Link>
      <Link href="/me/what-i-use">
        <span class="border-2 border-indigo-500 p-3 rounded-full cursor-pointer">
          <AiOutlineArrowRight size={24} class="text-[#FBAE95]" />
        </span>
      </Link>
    </div>
  </div> -->
</div>
